// <auto-generated />
namespace E_Learning.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class topiclist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(topiclist));
        
        string IMigrationMetadata.Id
        {
            get { return "202002271445127_topiclist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
